version: '3'
services:
  server:
    build: ./env/server
    ports:
    - 9092:9092
    depends_on:
    - mysql
    - memcached
    - elasticsearch
    volumes:
    - ./code:/code
  mysql:
    image: percona
    volumes:
    - mysql_storage:/var/
    ports:
    - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  memcached:
    image: memcached
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    environment:
    - "discovery.type=single-node"
    volumes:
    - eshd:/usr/share/elasticsearch/data
volumes:
  mysql_storage: {}
  eshd: {}